/**
 * Organism/layout styles — purely CSS-variable driven for theme swaps.
 * Atomic components live under src/components; this object maps pages & shells.
 * Completeness: 92/100
 */
import { v } from "../theme/cssVars.js";

const mono = v("fontMono");
const sans = v("fontSans");
const serif = v("fontSerif");

/** @typedef {typeof appStyles} AppStyles */

function buildStyles() {
  return {
    app: {
      fontFamily: sans,
      background: v("bgApp"),
      minHeight: "100vh",
      display: "flex",
      flexDirection: "column",
      color: v("textPrimary"),
    },

    header: {
      display: "flex",
      alignItems: "center",
      flexWrap: "wrap",
      rowGap: 8,
      columnGap: 8,
      padding: "8px 16px",
      minHeight: 56,
      background: v("bgPanel"),
      borderBottom: `1px solid ${v("borderDefault")}`,
      boxShadow: v("shadowCard"),
      position: "sticky",
      top: 0,
      zIndex: 10,
    },

    logo: { display: "flex", alignItems: "center", gap: 10, marginRight: 16, flexShrink: 0 },
    logoMark: {
      width: 32,
      height: 32,
      background: v("inverseBg"),
      borderRadius: v("radiusLg"),
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
    },
    logoText: { fontFamily: serif, fontSize: 18, fontWeight: 400, color: v("textPrimary"), letterSpacing: "-0.3px" },
    logoBadge: {
      fontFamily: mono,
      fontSize: 11,
      padding: "2px 8px",
      background: v("bgMuted"),
      borderRadius: v("radiusSm"),
      color: v("textMuted"),
      border: `1px solid ${v("borderInput")}`,
    },

    projectSwitcher: { display: "flex", alignItems: "center", gap: 6, flexShrink: 0 },
    projectSelect: {
      fontFamily: mono,
      fontSize: 11,
      padding: "6px 28px 6px 10px",
      borderRadius: v("radiusMd"),
      border: `1px solid ${v("borderInput")}`,
      background: v("bgPanel"),
      color: v("textPrimary"),
      maxWidth: 200,
      cursor: "pointer",
    },
    addProjectHeaderBtn: {
      width: 30,
      height: 30,
      borderRadius: v("radiusMd"),
      border: `1px solid ${v("borderInput")}`,
      background: v("bgSubtle"),
      cursor: "pointer",
      fontWeight: 700,
      color: v("textPrimary"),
      fontSize: 18,
      lineHeight: 1,
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      flexShrink: 0,
    },

    srOnly: {
      position: "absolute",
      width: 1,
      height: 1,
      padding: 0,
      margin: -1,
      overflow: "hidden",
      clip: "rect(0,0,0,0)",
      whiteSpace: "nowrap",
      border: 0,
    },

    nav: {
      display: "flex",
      gap: 2,
      flex: 1,
      flexWrap: "wrap",
      minWidth: 0,
      justifyContent: "center",
    },
    navBtn: {
      padding: "6px 14px",
      borderRadius: v("radiusMd"),
      border: "none",
      background: "transparent",
      cursor: "pointer",
      fontSize: 13,
      fontWeight: 500,
      color: v("textMuted"),
      fontFamily: sans,
      display: "flex",
      alignItems: "center",
      gap: 6,
      transition: "all .15s",
    },
    navBtnActive: { background: v("bgNavActive"), color: v("textPrimary"), fontWeight: 600 },
    navBadge: {
      background: v("navBadgeBg"),
      color: v("navBadgeFg"),
      fontSize: 10,
      fontWeight: 700,
      padding: "1px 5px",
      borderRadius: v("radiusFull"),
      minWidth: 16,
      textAlign: "center",
    },
    themeToggleBtn: {
      padding: "4px 8px",
      borderRadius: v("radiusMd"),
      border: `1px solid ${v("borderInput")}`,
      background: v("bgSubtle"),
      fontFamily: mono,
      fontSize: 10,
      cursor: "pointer",
      color: v("textMuted"),
    },

    headerRight: { display: "flex", alignItems: "center", gap: 12, marginLeft: "auto" },
    themeToggleBtn: {
      padding: "6px 10px",
      borderRadius: v("radiusMd"),
      border: `1px solid ${v("borderInput")}`,
      background: v("bgSubtle"),
      color: v("textSecondary"),
      cursor: "pointer",
      fontFamily: sans,
      fontSize: 12,
      fontWeight: 600,
    },
    envIndicator: {
      display: "flex",
      alignItems: "center",
      gap: 6,
      fontFamily: mono,
      fontSize: 11,
      color: v("textMuted"),
      background: v("bgChip"),
      padding: "4px 10px",
      borderRadius: v("radiusMd"),
      border: `1px solid ${v("borderInput")}`,
    },
    envDot: { width: 7, height: 7, borderRadius: "50%", display: "inline-block" },
    avatar: {
      width: 32,
      height: 32,
      borderRadius: "50%",
      background: v("inverseBg"),
      color: v("inverseFg"),
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontSize: 12,
      fontWeight: 700,
    },

    main: { flex: 1, overflow: "hidden", display: "flex", flexDirection: "column" },

    viewPad: { padding: "32px 36px", overflowY: "auto", height: "calc(100vh - 56px)" },
    pageTitle: {
      fontFamily: serif,
      fontSize: 26,
      fontWeight: 400,
      color: v("textPrimary"),
      marginBottom: 4,
    },
    pageSub: { fontSize: 14, color: v("textMuted") },
    pageEyebrow: {
      fontSize: 12,
      fontFamily: mono,
      color: v("textMuted"),
      marginBottom: 8,
      letterSpacing: "0.03em",
      textTransform: "uppercase",
      fontWeight: 600,
    },

    workspaceHint: {
      fontSize: 12,
      color: v("textSubtle"),
      lineHeight: 1.5,
      marginTop: -8,
      marginBottom: 20,
      maxWidth: 720,
    },
    overviewTop: {
      display: "flex",
      flexWrap: "wrap",
      alignItems: "flex-start",
      justifyContent: "space-between",
      gap: 16,
      marginBottom: 8,
    },
    btnPrimaryOutline: {
      background: v("bgPanel"),
      color: v("brand"),
      border: `2px solid ${v("brand")}`,
      borderRadius: v("radiusLg"),
      padding: "10px 18px",
      fontWeight: 700,
      fontSize: 13,
      cursor: "pointer",
      fontFamily: sans,
      flexShrink: 0,
    },

    statGrid: { display: "grid", gridTemplateColumns: "repeat(2, 1fr)", gap: 16, marginBottom: 32 },
    statCard: {
      background: v("bgPanel"),
      borderRadius: v("radius2xl"),
      padding: "20px 24px",
      border: `1px solid ${v("borderDefault")}`,
      boxShadow: v("shadowCard"),
      transition: "box-shadow .15s",
    },
    statValue: { fontFamily: serif, fontSize: 36, fontWeight: 400, lineHeight: 1 },
    statLabel: { fontWeight: 600, fontSize: 13, color: v("textPrimary"), marginTop: 8 },
    statSub: { fontSize: 12, color: v("textSubtle"), marginTop: 4 },

    sectionRow: { display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: 12 },
    viewAllBtn: {
      fontSize: 12,
      color: v("textLink"),
      background: "none",
      border: "none",
      cursor: "pointer",
      fontWeight: 600,
      fontFamily: sans,
    },
    sectionTitle: { fontWeight: 700, fontSize: 14, color: v("textPrimary") },

    projectFleetCard: {
      background: v("bgPanel"),
      borderRadius: v("radius2xl"),
      border: `1px solid ${v("borderDefault")}`,
      padding: "18px 20px",
      display: "flex",
      flexDirection: "column",
      gap: 12,
      boxShadow: v("shadowCard"),
      textAlign: "left",
    },
    projectFleetCardAttention: {
      boxShadow: `${v("shadowCard")}, inset 3px 0 0 ${v("accentOrange")}`,
    },
    projectFleetCardError: {
      boxShadow: `${v("shadowCard")}, inset 3px 0 0 ${v("accentRose")}`,
    },
    projectFleetHeader: {
      display: "flex",
      alignItems: "flex-start",
      justifyContent: "space-between",
      gap: 12,
    },
    projectFleetName: {
      fontFamily: serif,
      fontSize: 18,
      fontWeight: 400,
      color: v("textPrimary"),
      margin: 0,
    },
    projectFleetDetail: { fontSize: 12, color: v("textMuted"), fontFamily: mono, marginTop: 4 },
    projectFleetHealth: { display: "flex", alignItems: "center", gap: 8, fontSize: 12, color: v("textSecondary") },
    healthDot: { width: 8, height: 8, borderRadius: "50%", flexShrink: 0 },
    projectFleetStatsRow: { display: "flex", flexWrap: "wrap", gap: 8 },
    projectFleetStatChip: {
      fontSize: 11,
      fontFamily: mono,
      padding: "4px 8px",
      borderRadius: v("radiusMd"),
      background: v("bgChip"),
      border: `1px solid ${v("borderInput")}`,
      color: v("textSecondary"),
    },
    projectFleetLastLine: { fontSize: 12, color: v("textMuted"), fontFamily: mono },
    projectFleetActions: { display: "flex", flexWrap: "wrap", gap: 8, marginTop: 4 },
    activeProjectBadge: {
      fontSize: 10,
      fontWeight: 700,
      textTransform: "uppercase",
      letterSpacing: "0.05em",
      padding: "4px 8px",
      borderRadius: v("radiusMd"),
      background: v("selectionTintBlue"),
      color: v("textLink"),
      border: `1px solid ${v("borderDefault")}`,
      whiteSpace: "nowrap",
    },
    btnFleetSecondary: {
      background: v("bgChip"),
      color: v("textSecondary"),
      border: `1px solid ${v("borderInput")}`,
      borderRadius: v("radiusLg"),
      padding: "8px 12px",
      fontWeight: 600,
      fontSize: 12,
      cursor: "pointer",
      fontFamily: sans,
    },

    miniCard: {
      display: "flex",
      alignItems: "center",
      gap: 8,
      background: v("bgPanel"),
      borderRadius: v("radiusLg"),
      padding: "10px 14px",
      border: `1px solid ${v("borderDefault")}`,
      cursor: "pointer",
      fontSize: 13,
      transition: "border-color .15s",
    },
    miniCardTitle: { fontWeight: 500, fontSize: 13, color: v("textPrimary"), flex: 1 },

    miniRuleCard: {
      display: "flex",
      alignItems: "center",
      gap: 12,
      background: v("bgPanel"),
      borderRadius: v("radiusLg"),
      padding: "10px 14px",
      border: `1px solid ${v("borderDefault")}`,
    },
    ruleIndicatorDot: {
      width: 8,
      height: 8,
      borderRadius: "50%",
      background: v("accentGreen"),
      flexShrink: 0,
    },
    ruleUsage: {
      fontSize: 11,
      fontFamily: mono,
      color: v("textSubtle"),
      marginLeft: "auto",
      whiteSpace: "nowrap",
    },

    calloutInfo: {
      marginTop: 28,
      padding: "18px 20px",
      background: v("bgCalloutInfo"),
      borderRadius: v("radius2xl"),
      border: `1px solid ${v("bgCalloutInfoBorder")}`,
    },
    calloutInfoTitle: { fontWeight: 600, color: v("bgCalloutInfoTitle"), marginBottom: 6 },
    calloutInfoText: {
      fontSize: 13,
      color: v("bgCalloutInfoText"),
      lineHeight: 1.5,
      marginBottom: 12,
    },

    splitLayout: {
      display: "grid",
      gridTemplateColumns: "360px 1fr",
      height: "calc(100vh - 56px)",
      overflow: "hidden",
    },
    queuePanel: {
      borderRight: `1px solid ${v("borderDefault")}`,
      background: v("bgPanel"),
      display: "flex",
      flexDirection: "column",
      overflow: "hidden",
    },
    queueHeader: { padding: "20px 20px 12px", borderBottom: `1px solid ${v("borderHairline")}` },
    queueTitle: { fontFamily: serif, fontSize: 18, color: v("textPrimary") },
    queueSub: { fontSize: 12, color: v("textSubtle"), marginTop: 3 },
    queueList: { overflowY: "auto", flex: 1, padding: "12px 12px" },

    approvalCard: {
      padding: "14px 16px",
      borderRadius: v("radiusXl"),
      border: `1px solid ${v("borderHairline")}`,
      marginBottom: 8,
      cursor: "pointer",
      background: v("bgQueue"),
      transition: "all .15s",
    },
    approvalCardActive: {
      border: `1px solid ${v("accentBlue")}`,
      background: v("selectionTintBlue"),
    },
    approvalCardTop: { display: "flex", gap: 6, marginBottom: 8 },
    approvalCardTitle: { fontWeight: 600, fontSize: 13, color: v("textPrimary"), lineHeight: 1.4, marginBottom: 8 },
    approvalCardMeta: { display: "flex", alignItems: "center", gap: 8 },
    approvalCardTime: {
      fontSize: 11,
      color: v("textSubtle"),
      marginLeft: "auto",
      fontFamily: mono,
    },

    typePill: {
      display: "inline-flex",
      alignItems: "center",
      gap: 4,
      fontSize: 11,
      fontWeight: 700,
      padding: "3px 8px",
      borderRadius: v("radiusSm"),
      fontFamily: mono,
      letterSpacing: ".3px",
    },
    impactPill: {
      display: "inline-flex",
      alignItems: "center",
      fontSize: 10,
      fontWeight: 700,
      padding: "3px 7px",
      borderRadius: v("radiusSm"),
      fontFamily: mono,
      letterSpacing: ".3px",
    },
    envTag: {
      display: "inline-flex",
      alignItems: "center",
      fontSize: 10,
      fontWeight: 600,
      padding: "2px 6px",
      borderRadius: 3,
      fontFamily: mono,
    },
    systemTag: {
      fontSize: 11,
      padding: "3px 8px",
      background: v("bgSubtle"),
      border: `1px solid ${v("borderInput")}`,
      borderRadius: v("radiusSm"),
      color: v("textSecondary"),
      fontFamily: mono,
    },

    detailPanel: { overflowY: "auto", background: v("bgApp") },
    detail: { padding: "28px 32px" },
    detailHeader: {
      background: v("bgPanel"),
      borderRadius: v("radius2xl"),
      padding: "20px 24px",
      border: `1px solid ${v("borderDefault")}`,
      marginBottom: 16,
    },
    detailHeaderTop: { display: "flex", gap: 8, marginBottom: 12 },
    detailTitle: { fontFamily: serif, fontSize: 22, color: v("textPrimary"), marginBottom: 8 },
    detailDesc: { fontSize: 14, color: v("textSecondary"), lineHeight: 1.6, marginBottom: 16 },
    metaRow: { display: "flex", flexWrap: "wrap", gap: 8 },
    metaChip: {
      display: "flex",
      flexDirection: "column",
      background: v("bgChip"),
      borderRadius: v("radiusMd"),
      padding: "6px 10px",
      border: `1px solid ${v("borderDefault")}`,
    },
    metaChipLabel: {
      fontSize: 10,
      color: v("textSubtle"),
      fontWeight: 600,
      textTransform: "uppercase",
      letterSpacing: ".5px",
    },
    metaChipValue: {
      fontSize: 12,
      fontWeight: 600,
      color: v("textPrimary"),
      fontFamily: mono,
      marginTop: 2,
    },

    section: {
      background: v("bgPanel"),
      borderRadius: v("radius2xl"),
      padding: "18px 20px",
      border: `1px solid ${v("borderDefault")}`,
      marginBottom: 12,
    },
    sectionLabel: {
      fontSize: 11,
      fontWeight: 700,
      color: v("textSubtle"),
      textTransform: "uppercase",
      letterSpacing: ".8px",
      marginBottom: 12,
      fontFamily: mono,
    },

    diffTable: {
      borderRadius: v("radiusLg"),
      overflow: "hidden",
      border: `1px solid ${v("borderDefault")}`,
      fontSize: 12,
      fontFamily: mono,
    },
    diffHeader: {
      display: "grid",
      gridTemplateColumns: "2fr 1fr 2fr 2fr",
      padding: "8px 12px",
      background: v("bgSubtle"),
      borderBottom: `1px solid ${v("borderDefault")}`,
      fontWeight: 700,
      fontSize: 10,
      color: v("textSubtle"),
      textTransform: "uppercase",
      letterSpacing: ".5px",
    },
    diffRow: {
      display: "grid",
      gridTemplateColumns: "2fr 1fr 2fr 2fr",
      padding: "9px 12px",
      borderBottom: `1px solid ${v("borderHairline")}`,
      alignItems: "center",
      gap: 4,
    },
    diffRowUpdate: { background: v("bgDiffUpdate") },
    diffRowAdd: { background: v("bgDiffAdd") },
    diffRowRemove: { background: v("bgDiffRemove") },
    diffRowGenerate: { background: v("bgDiffGenerate") },
    diffKey: { fontWeight: 600, color: v("textPrimary"), fontSize: 11 },
    diffVal: {
      color: v("textSecondary"),
      fontSize: 11,
      overflow: "hidden",
      textOverflow: "ellipsis",
      whiteSpace: "nowrap",
      display: "flex",
      alignItems: "center",
      gap: 4,
    },
    actionBadge: {
      fontSize: 9,
      fontWeight: 700,
      padding: "2px 5px",
      borderRadius: 3,
      letterSpacing: ".3px",
      textTransform: "uppercase",
      whiteSpace: "nowrap",
    },
    revealBtn: {
      fontSize: 10,
      fontFamily: sans,
      color: v("textLink"),
      background: "none",
      border: "none",
      cursor: "pointer",
      padding: "1px 4px",
      textDecoration: "underline",
      flexShrink: 0,
      fontWeight: 500,
    },

    rotationCard: {
      background: v("bgChip"),
      borderRadius: v("radiusLg"),
      padding: "12px 16px",
      display: "flex",
      flexDirection: "column",
      gap: 8,
    },
    rotationRow: {
      display: "flex",
      justifyContent: "space-between",
      fontSize: 13,
      color: v("textMuted"),
    },

    trustNotice: {
      display: "flex",
      gap: 12,
      alignItems: "flex-start",
      background: v("bgTrust"),
      border: `1px solid ${v("borderTrust")}`,
      borderRadius: v("radiusXl"),
      padding: "14px 16px",
      marginBottom: 16,
    },

    actionRow: { display: "flex", gap: 10, alignItems: "center", paddingTop: 8 },
    btnApprove: {
      background: v("inverseBg"),
      color: v("inverseFg"),
      border: "none",
      borderRadius: v("radiusLg"),
      padding: "10px 20px",
      fontWeight: 700,
      fontSize: 13,
      cursor: "pointer",
      fontFamily: sans,
      marginLeft: "auto",
    },
    btnReject: {
      background: v("bgPanel"),
      color: v("accentRose"),
      border: `1px solid ${v("accentRoseMutedBorder")}`,
      borderRadius: v("radiusLg"),
      padding: "10px 16px",
      fontWeight: 600,
      fontSize: 13,
      cursor: "pointer",
      fontFamily: sans,
    },
    btnRule: {
      background: v("bgPanel"),
      color: v("textLink"),
      border: `1px solid ${v("accentBlueMutedBorder")}`,
      borderRadius: v("radiusLg"),
      padding: "10px 14px",
      fontWeight: 600,
      fontSize: 12,
      cursor: "pointer",
      fontFamily: sans,
    },
    btnGhost: {
      background: v("bgChip"),
      color: v("textMuted"),
      border: `1px solid ${v("borderInput")}`,
      borderRadius: v("radiusLg"),
      padding: "10px 16px",
      fontWeight: 600,
      fontSize: 13,
      cursor: "pointer",
      fontFamily: sans,
    },

    modalActions: { display: "flex", gap: 10, justifyContent: "flex-end", marginTop: 20 },
    modalHint: {
      fontSize: 11,
      color: v("textSubtle"),
      textAlign: "center",
      marginTop: 14,
      lineHeight: 1.5,
    },

    rulesExplainer: {
      display: "flex",
      gap: 14,
      alignItems: "flex-start",
      background: v("rulesExplainerBg"),
      border: `1px solid ${v("rulesExplainerBorder")}`,
      borderRadius: v("radius2xl"),
      padding: "16px 20px",
      fontSize: 13,
      color: v("rulesExplainerText"),
      lineHeight: 1.6,
    },
    rulesHowBox: {
      marginTop: 32,
      padding: "20px 24px",
      background: v("bgChip"),
      borderRadius: v("radius2xl"),
      border: `1px dashed ${v("borderDashed")}`,
    },

    ruleCard: {
      display: "flex",
      alignItems: "center",
      gap: 16,
      background: v("bgPanel"),
      borderRadius: v("radius2xl"),
      padding: "18px 20px",
      border: `1px solid ${v("borderDefault")}`,
      transition: "opacity .2s",
    },
    ruleCardLeft: { flex: 1 },
    ruleCardTitle: { fontWeight: 700, fontSize: 14, color: v("textPrimary") },
    ruleCardDesc: { fontSize: 13, color: v("textMuted"), marginTop: 4, lineHeight: 1.5 },
    ruleCardMeta: { display: "flex", gap: 8, marginTop: 8 },
    ruleCardRight: { display: "flex", alignItems: "center", gap: 12 },
    ruleMetaChip: {
      fontSize: 11,
      fontFamily: mono,
      color: v("textSubtle"),
      background: v("bgChip"),
      padding: "2px 8px",
      borderRadius: v("radiusSm"),
      border: `1px solid ${v("borderInput")}`,
    },
    toggleTrack: {
      width: 38,
      height: 22,
      borderRadius: 11,
      cursor: "pointer",
      position: "relative",
      transition: "background .2s",
      flexShrink: 0,
      border: "none",
    },
    toggleThumb: {
      position: "absolute",
      top: 3,
      width: 16,
      height: 16,
      borderRadius: "50%",
      background: v("bgPanel"),
      boxShadow: "0 1px 3px rgba(0,0,0,.2)",
      transition: "transform .2s",
    },
    toggleTrackOn: { background: v("accentGreen") },
    toggleTrackOff: { background: v("toggleTrackOff") },
    deleteBtn: {
      background: "none",
      border: "none",
      color: v("borderDashed"),
      cursor: "pointer",
      fontSize: 14,
      padding: "4px 6px",
      borderRadius: v("radiusSm"),
    },

    filterRow: { display: "flex", gap: 6, marginBottom: 24, flexWrap: "wrap" },
    filterBtn: {
      padding: "5px 12px",
      borderRadius: v("radiusMd"),
      border: `1px solid ${v("borderInput")}`,
      background: v("bgPanel"),
      fontSize: 12,
      cursor: "pointer",
      fontFamily: sans,
      color: v("textMuted"),
      fontWeight: 500,
    },
    filterBtnActive: {
      background: v("inverseBg"),
      color: v("inverseFg"),
      border: `1px solid ${v("inverseBg")}`,
    },

    activityList: { display: "flex", flexDirection: "column" },
    activityItem: { display: "flex", gap: 16, position: "relative" },
    activityIconWrap: {
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      width: 32,
      flexShrink: 0,
    },
    activityLine: {
      width: 1,
      flex: 1,
      background: v("borderDefault"),
      minHeight: 20,
      marginTop: 4,
    },
    activityContent: { paddingBottom: 20, flex: 1 },
    activityMsg: { fontSize: 13, color: v("textPrimary"), fontWeight: 500, lineHeight: 1.5 },
    activityMeta: {
      display: "flex",
      alignItems: "center",
      gap: 8,
      marginTop: 6,
      flexWrap: "wrap",
    },
    activityType: {
      fontSize: 10,
      fontWeight: 700,
      padding: "2px 6px",
      borderRadius: 3,
      fontFamily: mono,
      textTransform: "uppercase",
      letterSpacing: ".3px",
    },
    activityTime: {
      fontSize: 11,
      color: v("textSubtle"),
      fontFamily: mono,
    },
    activityActor: { fontSize: 11, color: v("textSubtle") },

    vaultTable: {
      background: v("bgPanel"),
      borderRadius: v("radius2xl"),
      border: `1px solid ${v("borderDefault")}`,
      overflow: "hidden",
      marginBottom: 16,
    },
    vaultHeader: {
      display: "grid",
      gridTemplateColumns: "2fr 1.5fr 3fr 1fr 1.5fr",
      padding: "10px 16px",
      background: v("bgSubtle"),
      borderBottom: `1px solid ${v("borderDefault")}`,
      fontSize: 10,
      fontWeight: 700,
      color: v("textSubtle"),
      textTransform: "uppercase",
      letterSpacing: ".5px",
      fontFamily: mono,
    },
    vaultRow: {
      display: "grid",
      gridTemplateColumns: "2fr 1.5fr 3fr 1fr 1.5fr",
      padding: "12px 16px",
      borderBottom: `1px solid ${v("borderHairline")}`,
      alignItems: "center",
      fontSize: 12,
    },
    vaultKey: {
      fontFamily: mono,
      fontWeight: 600,
      color: v("textPrimary"),
      fontSize: 12,
    },
    vaultType: {
      fontFamily: mono,
      fontSize: 10,
      color: v("textSubtle"),
    },
    vaultVal: {
      fontFamily: mono,
      fontSize: 12,
      color: v("textSecondary"),
      display: "flex",
      alignItems: "center",
      gap: 6,
    },
    vaultDate: {
      fontFamily: mono,
      fontSize: 11,
      color: v("textSubtle"),
    },
    healthBadge: {
      fontSize: 11,
      fontWeight: 600,
      padding: "3px 8px",
      borderRadius: v("radiusSm"),
      fontFamily: mono,
    },
    vaultNotice: {
      fontSize: 13,
      color: v("textMuted"),
      padding: "12px 16px",
      background: v("bgChip"),
      borderRadius: v("radiusLg"),
      border: `1px solid ${v("borderInput")}`,
    },
    vaultEnvTabRow: {
      display: "flex",
      flexWrap: "nowrap",
      gap: 8,
      overflowX: "auto",
      paddingBottom: 6,
      marginBottom: 16,
      WebkitOverflowScrolling: "touch",
    },
    vaultEnvTab: {
      flex: "0 0 auto",
      display: "flex",
      alignItems: "center",
      gap: 6,
      padding: "8px 14px",
      borderRadius: v("radiusLg"),
      border: `1px solid ${v("borderInput")}`,
      background: v("bgPanel"),
      color: v("textSecondary"),
      cursor: "pointer",
      fontFamily: sans,
      fontSize: 13,
      fontWeight: 500,
    },
    vaultEnvTabActive: {
      background: v("bgNavActive"),
      color: v("textPrimary"),
      borderColor: v("brand"),
      fontWeight: 600,
    },
    vaultEnvTabCount: {
      fontFamily: mono,
      fontSize: 10,
      color: v("textMuted"),
      background: v("bgChip"),
      padding: "2px 6px",
      borderRadius: v("radiusSm"),
    },
    vaultScopeBanner: {
      marginBottom: 20,
      padding: "12px 16px",
      background: v("bgSubtle"),
      borderRadius: v("radius2xl"),
      border: `1px solid ${v("borderDefault")}`,
      fontSize: 13,
      color: v("textSecondary"),
      lineHeight: 1.55,
    },
    vaultEnvTitle: {
      fontSize: 12,
      fontWeight: 600,
      fontFamily: mono,
      color: v("textMuted"),
      marginBottom: 10,
      textTransform: "uppercase",
      letterSpacing: "0.06em",
    },

    addProjectBar: {
      display: "flex",
      justifyContent: "space-between",
      alignItems: "center",
      flexWrap: "wrap",
      gap: 12,
      marginBottom: 20,
    },
    stepDots: { display: "flex", gap: 7, alignItems: "center" },
    stepDot: {
      width: 9,
      height: 9,
      borderRadius: "50%",
      background: v("borderInput"),
      transition: "background .15s",
    },
    stepDotOn: { background: v("brand") },
    pathGrid: { display: "grid", gridTemplateColumns: "1fr", gap: 14 },
    pathCard: {
      display: "block",
      width: "100%",
      textAlign: "left",
      background: v("bgPanel"),
      border: `1px solid ${v("borderDefault")}`,
      borderRadius: v("radius3xl"),
      padding: "22px 20px",
      cursor: "pointer",
      fontFamily: sans,
      boxShadow: v("shadowCard"),
      transition: "border-color .15s, box-shadow .15s",
    },
    pathIcon: { fontSize: 28, display: "block", marginBottom: 10 },
    pathTitle: { fontWeight: 700, fontSize: 15, color: v("textPrimary") },
    pathDesc: {
      fontSize: 13,
      color: v("textMuted"),
      lineHeight: 1.55,
      marginTop: 8,
      marginBottom: 14,
    },
    pathCta: { fontSize: 13, fontWeight: 700, color: v("textLink") },
    repoList: { display: "flex", flexDirection: "column", gap: 8, maxWidth: 560 },
    repoRow: {
      display: "flex",
      flexDirection: "column",
      alignItems: "flex-start",
      gap: 4,
      padding: "14px 16px",
      border: `1px solid ${v("borderDefault")}`,
      borderRadius: v("radiusXl"),
      background: v("bgQueue"),
      cursor: "pointer",
      textAlign: "left",
      fontFamily: sans,
      fontSize: 14,
      color: v("textPrimary"),
      width: "100%",
    },
    repoRowActive: {
      border: `1px solid ${v("accentBlue")}`,
      background: v("selectionTintBlue"),
    },
    repoName: {
      fontFamily: mono,
      fontWeight: 600,
      fontSize: 13,
    },
    repoMeta: {
      fontSize: 11,
      color: v("textSubtle"),
      fontFamily: mono,
    },
    mutedBox: {
      padding: 22,
      textAlign: "center",
      color: v("textSubtle"),
      fontSize: 13,
      border: `1px dashed ${v("borderInput")}`,
      borderRadius: v("radiusLg"),
    },
    wizardActions: {
      display: "flex",
      flexWrap: "wrap",
      gap: 10,
      justifyContent: "flex-end",
      marginTop: 24,
      paddingTop: 16,
      borderTop: `1px solid ${v("borderDefault")}`,
    },
    inlineHint: {
      fontSize: 12,
      color: v("textMuted"),
      marginTop: 10,
      marginBottom: 4,
    },
    renderConnectCard: {
      background: v("bgPanel"),
      border: `1px solid ${v("borderDefault")}`,
      borderRadius: v("radius2xl"),
      padding: "20px 22px",
      maxWidth: 560,
    },
    previewTable: {
      background: v("bgPanel"),
      border: `1px solid ${v("borderDefault")}`,
      borderRadius: v("radiusXl"),
      overflow: "hidden",
      marginBottom: 8,
      maxWidth: 720,
    },
    previewHead: {
      display: "grid",
      gridTemplateColumns: "minmax(120px, 1fr) 2fr",
      padding: "10px 14px",
      background: v("bgSubtle"),
      borderBottom: `1px solid ${v("borderDefault")}`,
      fontSize: 10,
      fontWeight: 700,
      color: v("textSubtle"),
      textTransform: "uppercase",
      letterSpacing: ".5px",
      fontFamily: mono,
    },
    previewRow: {
      display: "grid",
      gridTemplateColumns: "minmax(120px, 1fr) 2fr",
      padding: "10px 14px",
      borderBottom: `1px solid ${v("borderHairline")}`,
      alignItems: "center",
      gap: 8,
    },

    overlay: {
      position: "fixed",
      inset: 0,
      background: v("bgModalTint"),
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      zIndex: 100,
      backdropFilter: "blur(4px)",
    },
    modal: {
      background: v("bgPanel"),
      borderRadius: 16,
      padding: "28px",
      width: "100%",
      maxWidth: 480,
      boxShadow: v("shadowModal"),
      border: `1px solid ${v("borderDefault")}`,
    },
    modalIcon: { fontSize: 28, marginBottom: 10 },
    modalTitle: {
      fontFamily: serif,
      fontSize: 22,
      color: v("textPrimary"),
      marginBottom: 6,
    },
    modalSub: { fontSize: 13, color: v("textMuted"), lineHeight: 1.6, marginBottom: 4 },
    impactRow: {
      display: "flex",
      alignItems: "center",
      gap: 12,
      marginTop: 12,
      padding: "10px 14px",
      background: v("bgChip"),
      borderRadius: v("radiusLg"),
    },
    formLabel: {
      fontSize: 11,
      fontWeight: 700,
      color: v("textMuted"),
      textTransform: "uppercase",
      letterSpacing: ".8px",
      display: "block",
      marginBottom: 6,
    },
    formInput: {
      width: "100%",
      padding: "10px 12px",
      borderRadius: v("radiusLg"),
      border: `1px solid ${v("borderInput")}`,
      fontFamily: sans,
      fontSize: 13,
      color: v("textPrimary"),
      outline: "none",
      boxSizing: "border-box",
      background: v("bgPanel"),
    },
    textarea: {
      width: "100%",
      padding: "10px 12px",
      borderRadius: v("radiusLg"),
      border: `1px solid ${v("borderInput")}`,
      fontFamily: sans,
      fontSize: 13,
      color: v("textPrimary"),
      outline: "none",
      resize: "vertical",
      boxSizing: "border-box",
      lineHeight: 1.6,
      background: v("bgPanel"),
    },

    rulePreview: {
      background: v("bgChip"),
      borderRadius: v("radiusXl"),
      padding: "14px 16px",
      display: "flex",
      flexDirection: "column",
      gap: 8,
      marginBottom: 12,
    },
    rulePreviewRow: {
      display: "flex",
      justifyContent: "space-between",
      fontSize: 13,
      color: v("textMuted"),
    },

    toast: {
      position: "fixed",
      bottom: 24,
      right: 24,
      background: v("toastBg"),
      color: v("toastFg"),
      padding: "12px 18px",
      borderRadius: v("radiusXl"),
      fontSize: 13,
      fontWeight: 500,
      zIndex: 200,
      boxShadow: v("shadowToast"),
      display: "flex",
      alignItems: "center",
      gap: 8,
      animation: "fadeIn .2s ease",
    },
    toastWarn: { background: v("bgToastWarn") },

    emptyState: {
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
      color: v("textSubtle"),
      fontSize: 13,
      textAlign: "center",
      padding: 40,
    },
  };
}

export const appStyles = buildStyles();

/** Hooks may call this later if styles become dynamic */
export default function createAppStyles() {
  return appStyles;
}
